### ISSUE TITLE
All AppVeyor builds are failing

### ISSUE THREAD

**Issue by jdufresne** [ionelmc/python-tblib#26]
For example,

https://ci.appveyor.com/project/ionelmc/python-tblib/build/master-50

This make contributing more difficult as each PR shows a build failure. It is hard to know if a change is introducing a regression or simply failing as before.

**Comment by ionelmc** [comment]
@jdufresne i'm looking at the failures now. 

PS. I plan to do a 1.4.0 release today after sorting out the CI.

**Comment by ionelmc** [comment]
Released `v1.4.0`.
