### ISSUE TITLE
Incompatible with Python 3.8

### ISSUE THREAD

**Issue by jamadden** [ionelmc/python-tblib#42]
The constructor for the `CodeType` changed in 3.8; to remedy that going forward, 3.8 introduced a `replace()` method that can be used instead. 

This was reported as a bug (with corresponding PR!) against gevent's local copy of tblib in https://github.com/gevent/gevent/pull/1429 by @vstinner

**Comment by ionelmc** [comment]
Alright lets see if I can cherrypick that commit.

**Comment by jamadden** [comment]
Thanks!
